#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

./download_deps

filename="SoomlaAndroidCore"
rm -rf build/
mkdir build
ant -buildfile soomla-android-core.xml -Dsoomla.filename="$filename" all

cd - > /dev/null
