#!/bin/sh

set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

ANDROID_CORE_CACHE=~/.soomla/cache/android-core
mkdir -p $ANDROID_CORE_CACHE

mkdir -p libs

SQUARE_OTTO_NAME=square-otto-1.3.2.jar
if [ ! -f libs/$SQUARE_OTTO_NAME ];
then
    if [ ! -f $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME ];
    then
        curl -o $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME.tmp https://cloud.github.com/downloads/square/otto/square-otto-1.3.2.jar
        mv $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME.tmp $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME
    fi
    cp $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME libs/$SQUARE_OTTO_NAME
fi