#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

build=../build/ios

rm -rf $build
mkdir -p $build

soomla-native/projects/cocos2dx-ios-core/build_all

cp -R submodules/soomla-ios-core/build/* $build/
cp -R soomla-native/projects/cocos2dx-ios-core/build/* $build/

cd - > /dev/null
