#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

ANDROID_STORE_CACHE=~/.soomla/cache/android-store
mkdir -p $ANDROID_STORE_CACHE

BILLING_JAR_NAME=IInAppBillingService.jar
if [ ! -d libs/$BILLING_JAR_NAME ];
then
    if [ ! -f $ANDROID_STORE_CACHE/$BILLING_JAR_NAME ];
    then
        curl -L -o $ANDROID_STORE_CACHE/$BILLING_JAR_NAME.tmp http://library.soom.la/fetch/android-store-google-play-iab/3?cf=dl_deps
        mv $ANDROID_STORE_CACHE/$BILLING_JAR_NAME.tmp $ANDROID_STORE_CACHE/$BILLING_JAR_NAME
    fi
    cp $ANDROID_STORE_CACHE/$BILLING_JAR_NAME libs/$BILLING_JAR_NAME
fi