#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

build=../build/android

rm -rf $build
mkdir -p $build

soomla-native/projects/cocos2dx-android-store/build_all

cp -R submodules/android-store/build/* $build/
cp -R soomla-native/projects/cocos2dx-android-store/build/* $build/

# handle special case of build_all location for android-store
cp -L submodules/android-store/build/AndroidStore.jar $build/
cp -R submodules/android-store-google-play/build/billing-services $build/
cp -R submodules/android-store-amazon/build/billing-services $build/

cd - > /dev/null
